### ISSUE TITLE
makeChains.py

### ISSUE THREAD

**Issue by billdred** [capnrefsmmat/seuss#6]
Hello,

I've been following your instructions for setting up this bot and keep getting syntax errors when trying to run makeChains.py almost entirely around missing parentheses in print calls, which I tried to remedy. This one has me stumped, as I'm not really strong in python syntax at all.

  File "makeChains.py", line 48
    deleteChainCache(sys.argv[1], "cache/")

If you could help me out I would really appreciate it, this really looks interesting to work with. The problem could be entirely user error. Everything up to this point has gone smoothly though.

Thank you,

-billdred

**Comment by TangerineCat** [comment]
You are likely running this on python3 when this code was clearly written for python2. Yes if that is the case you'll need to do a conversion, and you may have made an error while doing so.

**Comment by billdred** [comment]
Thanks, I believe I was able to get to the same point using python 2 and received the following errors. I did successfully set up the database.

root@BilldredMachine:/home/billdred/seuss# python ./makeChains.py DJG
Deleting old cache files
Creating new cache files
Traceback (most recent call last):
  File "./makeChains.py", line 51, in <module>
    makeChain(sys.argv[1], "sources/", "cache/")
  File "./makeChains.py", line 13, in makeChain
    fwd = Markov.MarkovChain(cacheDir + name + "-fwd", 1, True)
  File "/home/billdred/seuss/Markov.py", line 13, in __init__
    writeback = wb)
  File "/usr/lib/python2.7/shelve.py", line 239, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python2.7/shelve.py", line 223, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
  File "/usr/lib/python2.7/dbhash.py", line 18, in open
    return bsddb.hashopen(file, flag, mode)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 364, in hashopen
    d.open(file, db.DB_HASH, flags, mode)
bsddb.db.DBNoSuchFileError: (2, 'No such file or directory')

Thanks.
